name: Harry McLaverty
favicon: null
layout_spectrum: 0.65480588353239
typography_spectrum: 0.3533875197172165
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.4641826453153044
  lightness: 0.9201302649453282
  saturation: 0.4865512035321444
  rhythmicContrast: 0.8339099728036672
purpose: []
